---
theme: jekyll-theme-modernist
title: Isotropos
timezone: Spain
collections:
posts:
title: Posts
output: true
permalink:
description: Revista online de crítica cultural. Lecturas personales de literatura, cómic, cine y teleseries.
